kind: pipeline
name: deploy_portfolio
type: docker

trigger:
  branch:
    - develop

steps:
  - name: build
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - yarn
      - yarn build

  - name: merge_and_push
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - git config --global user.email "drone_ci@iamon99.com"
      - git config --global user.name "drone_ci"
      - git merge --ff-only develop
      - git push
    when:
      status: [success]

---
kind: pipeline
type: exec
name: default

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - master

steps:
  - name: up
    commands:
      - echo hello world
