kind: pipeline
name: deploy_portfolio
type: docker

steps:
  - name: build_and_deploy
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - yarn
      - yarn build

---
kind: pipeline
type: exec
name: default

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - preview
  event:
    include:
      - pull_request

steps:
  - name: up
    commands:
      - echo hello world
