kind: pipeline
type: docker
name: build_test_merge

trigger:
  branch:
    - develop

steps:
  - name: build
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - yarn
      - yarn build

  - name: merge_and_push
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - git config --global user.email "drone_ci@iamon99.com"
      - git config --global user.name "drone_ci"
      - git checkout master
      - git merge --ff-only develop
      - git push origin master

    when:
      status: [success]

---
kind: pipeline
type: exec
name: deploy_portfolio

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - master

steps:
  - name: up
    commands:
      - cd nextjs-portfolio-tryout
      - yarn
      - yarn docker_rebuild
