kind: pipeline
name: deploy_portfolio
type: docker

steps:
  - name: build_and_deploy
    image: node:18
    commands:
      - cd nextjs-portfolio-tryout
      - yarn
      - yarn build
      - yarn docker_rebuild
