# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm
  - pip

import:
  - credentials.yml
  - .travis-merger.yml
  - .travis-stages.yml
  # - nextjs-tryout/.travis.yml
