# CREDIT: https://github.com/shren207/nextjs-docker-compose
version: '3.8'

services:
  next:
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
    working_dir: /app
    volumes:
      - $PWD:/app
      - node_modules:/app/node_modules
    command: sleep infinity

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio-http.rule=Host(`portfolio.iamon99.com`)'
      - 'traefik.http.routers.portfolio-http.entrypoints=web'
      - 'traefik.http.routers.portfolio-http.middlewares=portfolio-https'
      - 'traefik.http.middlewares.portfolio-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.portfolio.rule=Host(`portfolio.iamon99.com`)'
      - 'traefik.http.routers.portfolio.entrypoints=websecure'
      - 'traefik.http.routers.portfolio.tls.certresolver=myresolver'
      - 'traefik.http.services.portfolio.loadbalancer.server.port=3000'
# networks:
#   default:
#     external:
#       name: traefik-proxy-network

volumes:
  node_modules:
