# CREDIT: https://github.com/shren207/nextjs-docker-compose
version: '3.8'

services:
  next:
    build: .
    ports:
      - '8082:3000'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio.rule=Host(`portfolio.iamon99.com`)'
      - 'traefik.http.routers.portfolio.entrypoints=websecure'
      - 'traefik.http.routers.portfolio.tls.certresolver=myresolver'
      - 'traefik.http.services.portfolio.loadbalancer.server.port=8082'

networks:
  default:
    external:
      name: traefik-proxy-network
