name: master_build
on:
  push:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  nextjs-portfolio-tryout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run test
        run: |
          cd nextjs-portfolio-tryout
            yarn
            yarn init_test
          cd ..

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: nextjs-portfolio-tryout_screenshots
          path: |
            nextjs-portfolio-tryout/cypress/screenshots

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: routine-check
          slack_username: Github
          status: failure
        if: failure()
